```yaml name=.github/workflows/build.yml
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # OPTIONAL: Add test step here if you have tests
      # - name: Run tests
      #   run: npm test

      # OPTIONAL: Deploy step (customize for your deployment target)
      # - name: Deploy
      #   run: echo "Add your deployment script here"
```
